blog/urls.py
from django.conf.urls import include, url
from blog import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^posts/$', views.post_list, name='post_list'),
    url(r'^posts/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^posts/new/$', views.post_new, name='post_new'),
    url(r'^posts/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^posts/(?P<post_pk>\d+)/comments/new/$', views.comment_new, name='comment_new'),
    url(r'^posts/(?P<post_pk>\d+)/comments/(?P<pk>\d+)/edit/$', views.comment_edit, name='comment_edit'),

    url(r'^api/v1/', include('blog.api.v1', namespace='api_v1')),
    url(r'^api/v2/', include('blog.api.v2', namespace='api_v2')),
]

programming/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django import forms
from django.conf import settings
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from programming.utils import random_name_upload_to


def min_length_validator(value):
    if len(value) < 3:
        raise forms.ValidationError('3글자 이상 입력하라고 !!!')


class PhoneField(models.CharField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('max_length', 11)
        super(PhoneField, self).__init__(*args, **kwargs)
        validator = RegexValidator(r'^01[016789]\d{7,8}$',
                message='휴대폰 번호를 입력해주세요.')
        self.validators.append(validator)


@python_2_unicode_compatible
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=100,
            validators=[min_length_validator],
            help_text='포스팅 제목을 100자 이내로 써주세요.')
    content = models.TextField()
    photo = models.ImageField(blank=True, upload_to=random_name_upload_to)
    phone = PhoneField(blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.pk])

    def as_dict(self):
        return {
            'id': self.pk,
            'title': self.title,
            'phone': self.phone,
        }


@python_2_unicode_compatible
class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    message = models.TextField()

    def __str__(self):
        return self.message


@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import Post, Comment


class PostForm(forms.ModelForm):
    is_agree = forms.BooleanField(label='약관동의',
            error_messages={'required': '약관에 동의해주셔야, 서비스 이용이 가능합니다.'})

    class Meta:
        model = Post
        fields = ['title', 'content', 'photo', 'phone', 'tags']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # fields = '__all__'
        fields = ['message']

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
# from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import DetailView
from blog.models import Post, Comment
from blog.forms import PostForm, CommentForm


def owner_required(model_cls, user_field_name='author'):
    def wrap(fn):
        def inner_wrap(request, *args, **kwargs):
            request.instance = get_object_or_404(model_cls, pk=kwargs['pk'])
            if getattr(request.instance, user_field_name) != request.user:
                return HttpResponseForbidden('forbidden')
            return fn(request, *args, **kwargs)
        return inner_wrap
    return wrap


def index(request):
    return render(request, 'blog/index.html')


def post_list(request):
    post_list = Post.objects.all()
    params = {'post_list': post_list}
    return render(request, 'blog/post_list.html', params)


'''
def post_detail(request, pk):
    # post = Post.objects.get(pk=pk)
    post = get_object_or_404(Post, pk=pk)
    params = {'post': post}
    return render(request, 'blog/post_detail.html', params)
'''


class PostDetailView(DetailView):
    def get_object(self, queryset=None):
        # self.kwargs : year, month, day, pk
        # self.kwargs['year']
        # try:
        #     return Post.objects.get(pk=self.kwargs['pk'])
        # except Post.DoesNotExist:
        #     raise Http404

        return get_object_or_404(Post, pk=self.kwargs['pk'])

# post_detail = DetailView.as_view(model=Post)
post_detail = PostDetailView.as_view()


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(post)
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {
        'form': form,
    })


@login_required
@owner_required(Post, 'author')
def post_edit(request, pk):
    # post = Post.objects.get(pk=pk)
    # post = get_object_or_404(Post, pk=pk)
    post = request.instance

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            return redirect(post)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {
        'form': form,
    })


@login_required
def comment_new(request, post_pk):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            # comment.post = Post.objects.get(pk=post_pk)
            comment.post = get_object_or_404(Post, pk=post_pk)
            comment.save()
            messages.info(request, '새로운 댓글을 등록했습니다.')
            return redirect(comment.post)
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {
        'form': form,
    })


@login_required
@owner_required(Comment, 'author')
def comment_edit(request, post_pk, pk):
    # comment = Comment.objects.get(pk=pk)
    # comment = get_object_or_404(Comment, pk=pk)
    comment = request.instance

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect(comment.post)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'blog/comment_form.html', {
        'form': form,
        })

blog/templates/blog/base.html
{% extends "base.html" %}

blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}
{% load bootstrap3 %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form action="" method="post">
                    {% csrf_token %}

                    {# 한줄 주석 #}

                    {% comment %}
                    <table>
                        {{ form.as_table }}
                    </table>
                    {% endcomment %}

                    <div class="panel panel-default">
                        <div class="panel-heading"></div>
                        <div class="panel-body">
                            {% bootstrap_form form %}
                        </div>
                        <div class="panel-footer text-right">
                            <input type="submit" class="btn btn-primary" value="Submit" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}
	<div class="container">
		<div class="jumbotron">
			<h1>Ask Django</h1>
			<p>This is a template showcasing the optional theme stylesheet included in Bootstrap. Use it as a starting point to create something more unique by building on or modifying it.</p>
		</div>

		<a class="btn btn-primary">Primary Button</a>
		<a class="btn btn-info">Info Button</a>
		<a class="btn btn-success">Success Button</a>
		<a class="btn btn-danger">Danger Button</a>
	</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <p>
                <a href="{% url "blog:post_list" %}" class="btn btn-default">글목록</a>
            </p>

            <div class="panel panel-info">
                <div class="panel-heading">
                    {{ post.title }}
                </div>
                <div class="panel-body">
                    {% if post.photo %}
                        <img src="{{ post.photo.url }}" />
                    {% endif %}

                    {{ post.content|linebreaks }}
                </div>
            </div>

            <a href="{% url "blog:comment_new" post.pk %}" class="btn btn-primary btn-block">
                새 댓글 쓰기
            </a>

            <ul>
                {% for comment in post.comment_set.all %}
                    <li>
                        {{ comment.message }}
                        <a href="{% url "blog:comment_edit" post.pk comment.pk %}">수정</a>
                    </li>
                {% empty %}
                    <li>등록된 댓글이 없습니다.</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load bootstrap3 %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {# 한줄 주석 #}

                    {% comment %}
                    <table>
                        {{ form.as_table }}
                    </table>
                    {% endcomment %}

                    <div class="panel panel-default">
                        <div class="panel-heading"></div>
                        <div class="panel-body">
                            {% bootstrap_form form %}
                        </div>
                        <div class="panel-footer text-right">
                            <input type="submit" class="btn btn-primary" value="Submit" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>title</th>
                    </tr>
                </thead>
                <body>
                {% for post in post_list %}
                    <tr>
                        <td>
                            {{ post.id }}
                        </td>
                        <td>
                            <a href="{% url "blog:post_detail" post.pk %}">
                                {{ post.title }}
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </body>
            </table>
        </div>
    </div>
</div>

{% endblock %}